######################################################################
#  Project  blink with ThreadX
######################################################################

BINARY		=  blink
SRCFILES	= blink.c  miniprintf.c cortexm3_crt0.S cortexm3_vectors.S tx_initialize_low_level.S

all: elf bin

include ../../Makefile.incl

# End
